# Generated by Django 4.2.7 on 2025-08-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueamenity',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_amenities', to='courts.venue'),
        ),
    ]
