# Generated by Django 4.2.7 on 2025-08-12 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_add_available_days'),
        ('courts', '0004_venue_city'),
    ]

    operations = [
    ]
